//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ArgamanExpressEntities : DbContext
    {
        public ArgamanExpressEntities()
            : base("name=ArgamanExpressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Classification> Classifications { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Exclusivity> Exclusivitys { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertiesOwner> PropertiesOwners { get; set; }
        public virtual DbSet<Rental> Rentals { get; set; }
        public virtual DbSet<Street> Streets { get; set; }
        public virtual DbSet<SubProperty> SubProperties { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskType> TaskTypes { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual ObjectResult<getAllCities_Result> getAllCities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllCities_Result>("getAllCities");
        }
    
        public virtual ObjectResult<getAllDocuments_Result> getAllDocuments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllDocuments_Result>("getAllDocuments");
        }
    
        public virtual ObjectResult<getAllProperties_Result> getAllProperties()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllProperties_Result>("getAllProperties");
        }
    
        public virtual ObjectResult<getAllPropertiesOwners_Result> getAllPropertiesOwners()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllPropertiesOwners_Result>("getAllPropertiesOwners");
        }
    
        public virtual ObjectResult<getAllRentals_Result> getAllRentals()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllRentals_Result>("getAllRentals");
        }
    
        public virtual ObjectResult<getAllStreets_Result> getAllStreets()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllStreets_Result>("getAllStreets");
        }
    
        public virtual ObjectResult<getAllSubProperties_Result> getAllSubProperties()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllSubProperties_Result>("getAllSubProperties");
        }
    
        public virtual ObjectResult<getAllTasks_Result> getAllTasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllTasks_Result>("getAllTasks");
        }
    
        public virtual ObjectResult<getAllUsers_Result> getAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllUsers_Result>("getAllUsers");
        }
    
        public virtual ObjectResult<getStreets_Result> getStreets()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getStreets_Result>("getStreets");
        }
    }
}
